#!/usr/bin/env python3
"""
Grade-3 Pseudoscalar Field of the Earth
==========================================
Compute the anti-commutator {B, ∇B}₃ across the globe using the IGRF
geomagnetic field model. This is the standing pseudoscalar field —
the grade-3 content generated by the non-coplanarity of Earth's field.

In Cl(3,0), the pseudoscalar e₁₂₃ is central — the commutator [B,∇B]
cannot produce grade 3. But the anti-commutator {B, ∇B} CAN, through
the full geometric product of the field with its gradient.

For a pure bivector field B, {B₁, B₂} gives grades 0 and 2 only.
But Earth's field at each point has an effective FULL multivector
when we include:
  - The magnetic bivector B (grade 2)
  - The Coriolis/rotation effect on charges (grade 1 via v×Ω)
  - The telluric current density J = σ(v×B) (grade 1)

The grade-3 content is:
  {J_telluric, B_earth}₃ = {σ(v×B), B}₃

where v includes ocean currents, atmospheric winds, and core flow.

For the surface field, the simplest grade-3 proxy is the HELICITY:
  H = B · (∇×B) = B · μ₀J

This is the dot product of B with the current density — a pseudoscalar
that measures how much the field lines are twisted (linked/knotted).

The field helicity is nonzero wherever ∇×B ≠ 0 AND B has a component
along ∇×B — i.e., wherever the current is not perpendicular to B.
"""

import numpy as np
import sys, os

os.environ.setdefault("PYTHONIOENCODING", "utf-8")
if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

try:
    from pmagpy import pmag
    HAS_PMAGPY = True
except ImportError:
    HAS_PMAGPY = False
    print("WARNING: PmagPy not available. Using dipole approximation.")


# ─── IGRF dipole model (fallback) ──────────────────────────────────────

IGRF14_EPOCH_2025 = np.array([-29350.0, -1410.3, 4545.5])
IGRF14_SV_2025_2030 = np.array([12.6, 10.0, -21.5])


def igrf14_degree1_coefficients(year=2025.0):
    """Return IGRF-14 (g10, g11, h11) with 2025-2030 secular variation.

    IGRF-14 is predictive after epoch 2025.  We clamp this lightweight
    fallback to its published validity interval rather than extrapolating it.
    """
    offset = np.clip(float(year) - 2025.0, 0.0, 5.0)
    return tuple(IGRF14_EPOCH_2025 + offset * IGRF14_SV_2025_2030)


def dipole_field(lat_deg, lon_deg, year=2025.0):
    """IGRF-14 centered tilted-dipole fallback in local NED coordinates."""
    lat = np.radians(lat_deg)
    lon = np.radians(lon_deg)
    theta = np.pi / 2 - lat
    g10, g11, h11 = igrf14_degree1_coefficients(year)

    horizontal_dipole = g11 * np.cos(lon) + h11 * np.sin(lon)
    br = 2.0 * (g10 * np.cos(theta) + horizontal_dipole * np.sin(theta))
    btheta = g10 * np.sin(theta) - horizontal_dipole * np.cos(theta)
    bphi = g11 * np.sin(lon) - h11 * np.cos(lon)

    # Geographic north is -theta, east is +phi, and down is -radial.
    return -btheta, bphi, -br


def eval_field(lat, lon, year=2025.0):
    """Evaluate geomagnetic field at (lat, lon). Returns (Bx, By, Bz) in nT."""
    if HAS_PMAGPY:
        colat = 90.0 - lat
        elong = lon % 360.0
        try:
            # IGRF coefficients via PmagPy
            x, y, z, f = pmag.magsyn(None, None, year, year, 0, 0.0, colat, elong)
            return float(x), float(y), float(z)
        except Exception:
            pass
    return dipole_field(lat, lon, year)


# ─── Grade-3 computation ──────────────────────────────────────────────

def compute_grade3_map(nlat=90, nlon=180, year=2025.0):
    """
    Compute grade-3 proxies across the globe.

    Returns arrays on a lat×lon grid:
      - helicity: B · (∇×B) proxy (finite-difference curl)
      - noncoplanarity: |B × ∇B| / (|B||∇B|) = sin(angle between B and ∇B)
      - pseudoscalar_proxy: B_earth · Ω_earth (field-rotation dot product)
    """
    lats = np.linspace(-89, 89, nlat)
    lons = np.linspace(-179, 179, nlon)

    dlat = lats[1] - lats[0]
    dlon = lons[1] - lons[0]

    # Earth radius in km, for converting degrees to km
    R = 6371.0

    # Evaluate field on grid
    Bx = np.zeros((nlat, nlon))
    By = np.zeros((nlat, nlon))
    Bz = np.zeros((nlat, nlon))

    print(f"Evaluating field on {nlat}×{nlon} grid...")
    for i, lat in enumerate(lats):
        if i % 10 == 0:
            print(f"  lat={lat:.0f}°")
        for j, lon in enumerate(lons):
            Bx[i,j], By[i,j], Bz[i,j] = eval_field(lat, lon, year)

    # Field magnitude
    Bmag = np.sqrt(Bx**2 + By**2 + Bz**2)

    # Finite-difference gradients (∂B/∂lat, ∂B/∂lon)
    # Convert to physical distances
    dx = R * np.radians(dlon) * np.cos(np.radians(lats))[:, None]  # km per lon step
    dy = R * np.radians(dlat)  # km per lat step (constant)

    # Gradient of each component
    dBx_dlat = np.gradient(Bx, axis=0) / dy
    dBx_dlon = np.gradient(Bx, axis=1) / np.maximum(dx, 1.0)
    dBy_dlat = np.gradient(By, axis=0) / dy
    dBy_dlon = np.gradient(By, axis=1) / np.maximum(dx, 1.0)
    dBz_dlat = np.gradient(Bz, axis=0) / dy
    dBz_dlon = np.gradient(Bz, axis=1) / np.maximum(dx, 1.0)

    # ∇×B proxy (2D curl using horizontal gradients)
    # (∂Bz/∂y - ∂By/∂z, ∂Bx/∂z - ∂Bz/∂x, ∂By/∂x - ∂Bx/∂y)
    # We don't have ∂/∂z, so use horizontal components:
    # curl_z ≈ ∂By/∂x - ∂Bx/∂y (vertical component of curl)
    curl_z = dBy_dlon - dBx_dlat  # nT/km

    # Helicity proxy: B · (∇×B) ≈ Bz × curl_z (only vertical components)
    # This is the pseudoscalar — measures field line twist
    helicity = Bz * curl_z  # nT²/km

    # Non-coplanarity: how much does B rotate over a distance?
    # |∇B_direction| = angle change per km
    # Proxy: |B × (∂B/∂x)| / |B|² (the sine of the angle between B and its gradient)
    grad_Bmag = np.sqrt(dBx_dlat**2 + dBy_dlat**2 + dBz_dlat**2 +
                        dBx_dlon**2 + dBy_dlon**2 + dBz_dlon**2)

    # Cross product |B × ∇B| for non-coplanarity
    # Use B and ∂B/∂lat as the two vectors
    cross_x = By * dBz_dlat - Bz * dBy_dlat
    cross_y = Bz * dBx_dlat - Bx * dBz_dlat
    cross_z = Bx * dBy_dlat - By * dBx_dlat
    cross_mag = np.sqrt(cross_x**2 + cross_y**2 + cross_z**2)
    noncoplanarity = cross_mag / (Bmag * grad_Bmag + 1e-10)

    # Earth rotation pseudoscalar: B · Ω
    # Ω points along the rotation axis (geographic north)
    # In NED frame: Ω has only a "down" component at the pole,
    # only a "north" component at the equator
    # Ω_NED = (Ω cos(lat), 0, -Ω sin(lat)) where Ω = 7.292e-5 rad/s
    omega = 7.292e-5  # rad/s
    omega_x = omega * np.cos(np.radians(lats))[:, None]  # North component
    omega_z = -omega * np.sin(np.radians(lats))[:, None]  # Down component

    # B · Ω = Bx*Ωx + Bz*Ωz (pseudoscalar of field × rotation)
    field_rotation_ps = Bx * omega_x + Bz * omega_z  # nT × rad/s

    return lats, lons, {
        'Bmag': Bmag,
        'helicity': helicity,
        'noncoplanarity': noncoplanarity,
        'field_rotation_ps': field_rotation_ps,
        'curl_z': curl_z,
    }


# ─── Main ──────────────────────────────────────────────────────────────

if __name__ == "__main__":
    lats, lons, fields = compute_grade3_map(nlat=45, nlon=90)

    print("\n" + "=" * 70)
    print("GRADE-3 PSEUDOSCALAR FIELD OF THE EARTH")
    print("=" * 70)

    print(f"\nField magnitude |B|:")
    print(f"  Max: {fields['Bmag'].max():.0f} nT (at poles)")
    print(f"  Min: {fields['Bmag'].min():.0f} nT (at equator)")

    print(f"\nHelicity B·(∇×B) proxy:")
    print(f"  Max: {fields['helicity'].max():.2e} nT²/km")
    print(f"  Min: {fields['helicity'].min():.2e} nT²/km")
    print(f"  Std: {fields['helicity'].std():.2e} nT²/km")
    imax = np.unravel_index(np.argmax(np.abs(fields['helicity'])), fields['helicity'].shape)
    print(f"  Peak at: lat={lats[imax[0]]:.0f}°, lon={lons[imax[1]]:.0f}°")

    print(f"\nNon-coplanarity |B×∇B|/(|B||∇B|):")
    print(f"  Max: {fields['noncoplanarity'].max():.4f}")
    print(f"  Mean: {fields['noncoplanarity'].mean():.4f}")
    nc = fields['noncoplanarity']
    imax_nc = np.unravel_index(np.argmax(nc), nc.shape)
    print(f"  Peak at: lat={lats[imax_nc[0]]:.0f}°, lon={lons[imax_nc[1]]:.0f}°")

    print(f"\nField-rotation pseudoscalar B·Ω:")
    print(f"  Max: {fields['field_rotation_ps'].max():.4e} nT·rad/s (north pole)")
    print(f"  Min: {fields['field_rotation_ps'].min():.4e} nT·rad/s (south pole)")
    print(f"  Equator avg: {fields['field_rotation_ps'][len(lats)//2,:].mean():.4e}")

    # Latitude profile of the pseudoscalar
    print(f"\nLatitude profile of B·Ω:")
    for lat_idx in range(0, len(lats), len(lats)//8):
        lat = lats[lat_idx]
        ps = fields['field_rotation_ps'][lat_idx, :].mean()
        print(f"  {lat:+6.0f}°: {ps:+.4e} nT·rad/s")

    print(f"\nGrade-3 hotspots (helicity magnitude > 2σ):")
    threshold = 2 * fields['helicity'].std()
    hotspots = np.abs(fields['helicity']) > threshold
    if hotspots.any():
        hs_lats = lats[np.where(hotspots)[0]]
        hs_lons = lons[np.where(hotspots)[1]]
        for k in range(min(10, len(hs_lats))):
            print(f"  lat={hs_lats[k]:+6.0f}°, lon={hs_lons[k]:+7.0f}°: "
                  f"H={fields['helicity'][np.where(hotspots)[0][k], np.where(hotspots)[1][k]]:.2e}")

    print("\n" + "=" * 70)
    print("INTERPRETATION")
    print("=" * 70)
    print("""
The B·Ω pseudoscalar is the standing grade-3 field of the planet.
It is maximum at the magnetic poles (where B and Ω are most aligned)
and zero at points where B ⊥ Ω (roughly the magnetic equator but
shifted by the 11° tilt).

The helicity B·(∇×B) measures field-line twist — where the current
density has a component along B. This is nonzero wherever the field
has non-dipolar structure (quadrupole, octupole contributions create
twisted field lines).

The non-coplanarity |B×∇B|/(|B||∇B|) measures how much the field
direction rotates over distance — the condition for [F,∇F] ≠ 0.
This is maximum at the magnetic equator (where the field reverses
from pointing down to pointing up over a few thousand km).

Any process that couples to grade 3 (circular polarization of light,
chirality of molecules, helicity of fluid flow) is modulated by this
standing pseudoscalar field. The modulation is strongest at the poles
and weakest at the equator — a latitude-dependent grade-3 background.
""")
