#!/usr/bin/env python3
"""Physical boundaries among magnetic reversal, rotation, and core motion."""

try:
    from research_model_context import INNER_CORE_DOI
except ImportError:  # supports `python -m backend.reversal_physics`
    from backend.research_model_context import INNER_CORE_DOI


def reversal_physics_status() -> dict:
    return {
        "magnetic_reversal": {
            "what_changes": "the global magnetic-field polarity and geometry",
            "surface_rotation_flip": False,
            "status": "well established from paleomagnetic records",
        },
        "true_polar_wander": {
            "what_changes": "solid-Earth orientation relative to the spin axis",
            "rapid_planetary_tumble": False,
            "status": "slow reorientation is real; rapid whole-Earth flips are unsupported",
        },
        "inner_core": {
            "observed": (
                "differential rotation plus tentative localized deformation near "
                "the inner-core boundary"
            ),
            "field_anchored_to_solid_inner_core": False,
            "reason": "the geodynamo is generated by flow in the liquid outer core",
            "reversal_trigger_established": False,
            "source": f"https://doi.org/{INNER_CORE_DOI}",
        },
        "precession_countdown": {
            "supported": False,
            "reason": (
                "matching an average reversal interval to an integer number of "
                "precession cycles is not a validated accumulation law"
            ),
        },
    }


if __name__ == "__main__":
    status = reversal_physics_status()
    print("MAGNETIC REVERSAL / CORE-MOTION BOUNDARIES")
    for topic, details in status.items():
        print(f"\n{topic.replace('_', ' ').upper()}")
        for key, value in details.items():
            print(f"  {key}: {value}")
